codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"

ignore:
  - "cmd/main.go"  # Ignoring main.go in the cmd directory

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no