ignore:
  - "Classconnect-Courses-Service-Api/internals/dbConfig"
  - "Classconnect-Courses-Service-Api/internals/handlers"
  - "Classconnect-Courses-Service-Api/internals/repositories"
  - "Classconnect-Courses-Service-Api/main.go"